detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  FeatureEnvy:
    enabled: false
  UtilityFunction:
    enabled: false
  TooManyStatements:
    enabled: false
