require:
  - rubocop-performance
  - rubocop-rails
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  DisabledByDefault: true
  Exclude:
    - 'db/**/*'
